export const GET_LOCATIONS_PENDING = 'GET_LOCATIONS_PENDING'
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS'
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE'

export const GET_BOOKABLES_PENDING = 'GET_BOOKABLES_PENDING'
export const GET_BOOKABLES_SUCCESS = 'GET_BOOKABLES_SUCCESS'
export const GET_BOOKABLES_FAILURE = 'GET_BOOKABLES_FAILURE'

export const GET_BOOKINGS_PENDING = 'GET_BOOKINGS_PENDING'
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS'
export const GET_BOOKINGS_FAILURE = 'GET_BOOKINGS_FAILURE'

export const CREATE_BOOKING_PENDING = 'CREATE_BOOKING_PENDING'
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS'
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE'

export const DELETE_BOOKING_PENDING = 'DELETE_BOOKING_PENDING'
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS'
export const DELETE_BOOKING_FAILURE = 'DELETE_BOOKING_FAILURE'
